"""Initial schema with Enum classification and access_level

Revision ID: 52716868fb41
Revises: 
Create Date: 2025-11-26 01:41:31.371552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52716868fb41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objects', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('objects', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('objects', 'classification',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=True,
               existing_server_default=sa.text("'Unspecified'"))
    op.alter_column('objects', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True,
               existing_server_default=sa.text("'stored'"))
    op.create_foreign_key(None, 'objects', 'cameras', ['camera_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'objects', type_='foreignkey')
    op.alter_column('objects', 'status',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'stored'"))
    op.alter_column('objects', 'classification',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'Unspecified'"))
    op.alter_column('objects', 'name',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('objects', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
